import unittest
from template import templates

class render_template(unittest.TestCase):
  
  def test_render(self):
    kwargs = {
    'mirror': {
                'protocol': 'example_protocol',
                'host': 'example_host'
              },
    'os': {
            'distro': 'example_distro',
            'version': 'example_version',
            'appstream': 'example_appstream',
            'arch': 'example_arch'
          },
    'host': {
              'name': 'example_hostname'
            }
    }
    expected = '''# Generated by Anaconda 34.25.5.17
# Generated by pykickstart v3.32
#version=RHEL9
# Use graphical install
graphical
# Reboot after installation
reboot
repo --name="AppStream" --baseurl=example_protocol:://example_host/example_distro/example_version/example_appstream/example_arch/os

%post
%end

%addon com_redhat_kdump --enable --reserve-mb='auto'

%end

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=enp1s0 --ipv6=auto --activate
network  --hostname=example_hostname

# Use network installation
url --url="example_protocol://example_host/example_distro/example_version//example_arch/os"

%packages
@^server-product-environment
@remote-system-management

%end

# Run the Setup Agent on first boot
firstboot --enable

# Generated using Blivet version 3.6.0
ignoredisk --only-use=sdb,sda
autopart
# Partition clearing information
clearpart --none --initlabel

# System timezone
timezone America/Denver --utc

#Root password
rootpw --lock'''
    self.assertTrue(templates.render_template('kickstart.conf.j2', **kwargs) == expected)


if __name__ == '__main__':
  unittest.main()
